name: Test Package Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest setuptools

    - name: Update version for test build
      run: |
        # Update version in pyproject.toml for test builds
        sed -i "s/version = \".*\"/version = \"0.0.0-dev\"/" pyproject.toml

    - name: Build package
      run: |
        python -m build

    - name: Verify package contents
      run: |
        # Check that SQL files are included
        tar -tzf dist/*.tar.gz | grep -E "\.sql$" | head -10
        unzip -l dist/*.whl | grep -E "\.sql$" | head -10

        # Check that package structure is correct
        tar -tzf dist/*.tar.gz | grep "wmcoredb/" | head -10
        unzip -l dist/*.whl | grep "wmcoredb/" | head -10

    - name: Test package installation
      run: |
        pip install dist/*.whl --force-reinstall

        # Test that package can be installed (data-only package)
        echo "Package installed successfully"

    - name: Test data file access
      run: |
        # Count SQL files in the repository
        echo "Counting SQL files in repository..."
        repo_sql_count=$(find src/sql -name "*.sql" | wc -l)
        echo "Repository contains $repo_sql_count SQL files"

        # Count SQL files in the wheel
        echo "Counting SQL files in wheel..."
        wheel_sql_count=$(unzip -l dist/*.whl | grep -E "\.sql$" | wc -l)
        echo "Wheel contains $wheel_sql_count SQL files"

        # Compare counts
        if [ "$repo_sql_count" -eq "$wheel_sql_count" ]; then
          echo "✓ SQL file count matches: $repo_sql_count files"
        else
          echo "✗ SQL file count mismatch: repository has $repo_sql_count, wheel has $wheel_sql_count"
          echo "Repository files:"
          find src/sql -name "*.sql" | sort
          echo "Wheel files:"
          unzip -l dist/*.whl | grep -E "\.sql$" | sort
          exit 1
        fi

        # Show some sample files from the wheel
        echo "Sample SQL files in wheel:"
        unzip -l dist/*.whl | grep -E "\.sql$" | head -10

        # Simple test: just verify the package installed successfully
        echo "✓ Package installed successfully"
        echo "✓ Wheel contains SQL files"
        echo "✓ Data file access test passed"